export default {
    name: 'Finger Family Song', gimmick: 'T', params: {
        id: 'id-finger-family-song', partiture: [
            {ionicon: 'd', color: '#ffb700'},
            {ionicon: 'f#', color: '#ffb700'},
            {ionicon: 'a', color: '#ffb700'},
            {ionicon: 'a', color: '#ffb700'},
            {ionicon: 'd', color: '#ffb700'},
            {ionicon: 'f#', color: '#ffb700'},
            {ionicon: 'a', color: '#ffb700'},
            {ionicon: 'a', color: '#ffb700'},
            {ionicon: 'b', color: '#ffb700'},
            {ionicon: 'd', color: '#d900ff'},
            {ionicon: 'a', color: '#ffb700'},
            {ionicon: 'd', color: '#d900ff'},
            {ionicon: 'a', color: '#ffb700'},
            {ionicon: 'a', color: '#ffb700'},
            {ionicon: 'd', color: '#d900ff'},
            {ionicon: 'a', color: '#ffb700'},
            {ionicon: 'a', color: '#ffb700'},
            {ionicon: 'e', color: '#ffb700'},
            {ionicon: 'e', color: '#ffb700'},
            {ionicon: 'f#', color: '#ffb700'},
            {ionicon: 'd', color: '#ffb700'},
            {ionicon: 'd', color: '#ffb700'},
            {ionicon: 'f#', color: '#ffb700'},
            {ionicon: 'a', color: '#ffb700'},
            {ionicon: 'a', color: '#ffb700'},
            {ionicon: 'd', color: '#ffb700'},
            {ionicon: 'f#', color: '#ffb700'},
            {ionicon: 'a', color: '#ffb700'},
            {ionicon: 'a', color: '#ffb700'},
            {ionicon: 'b', color: '#ffb700'},
            {ionicon: 'd', color: '#d900ff'},
            {ionicon: 'a', color: '#ffb700'},
            {ionicon: 'd', color: '#d900ff'},
            {ionicon: 'a', color: '#ffb700'},
            {ionicon: 'a', color: '#ffb700'},
            {ionicon: 'd', color: '#d900ff'},
            {ionicon: 'a', color: '#ffb700'},
            {ionicon: 'a', color: '#ffb700'},
            {ionicon: 'e', color: '#ffb700'},
            {ionicon: 'f#', color: '#ffb700'},
            {ionicon: 'd', color: '#ffb700'}
        ]}
};