export default {
    name: 'Five little ducks', gimmick: 'T', params: {
        id: 'id-five-little-ducks', partiture: [
            {ionicon: 'd', color: '#d900ff'},
            {ionicon: 'd', color: '#d900ff'},
            {ionicon: 'd', color: '#d900ff'},
            {ionicon: 'd', color: '#d900ff'},
            {ionicon: 'f#', color: '#d900ff'},
            {ionicon: 'a', color: '#d900ff'},
            {ionicon: 'a', color: '#d900ff'},
            {ionicon: 'f#', color: '#d900ff'},
            {ionicon: 'd', color: '#d900ff'},
            {ionicon: 'e', color: '#d900ff'},
            {ionicon: 'e', color: '#d900ff'},
            {ionicon: 'e', color: '#d900ff'},
            {ionicon: 'e', color: '#d900ff'},
            {ionicon: 'f#', color: '#d900ff'},
            {ionicon: 'e', color: '#d900ff'},
            {ionicon: 'c#', color: '#d900ff'},
            {ionicon: 'a', color: '#ffb700'},
            {ionicon: 'd', color: '#d900ff'},
            {ionicon: 'd', color: '#d900ff'},
            {ionicon: 'd', color: '#d900ff'},
            {ionicon: 'd', color: '#d900ff'},
            {ionicon: 'f#', color: '#d900ff'},
            {ionicon: 'a', color: '#d900ff'},
            {ionicon: 'f#', color: '#d900ff'},
            {ionicon: 'd', color: '#d900ff'},
            {ionicon: 'd', color: '#d900ff'},
            {ionicon: 'e', color: '#d900ff'},
            {ionicon: 'e', color: '#d900ff'},
            {ionicon: 'a', color: '#ffb700'},
            {ionicon: 'c#', color: '#d900ff'},
            {ionicon: 'c#', color: '#d900ff'},
            {ionicon: 'd', color: '#d900ff'},
            {ionicon: 'd', color: '#d900ff'},
            {ionicon: 'd', color: '#d900ff'}
        ]}
};