export default {
    name: 'Frere Jacques', gimmick: 'T', params: {
        id: 'id-frere-jacques', partiture: [
            {color: '#d900ff', ionicon: 'c'},
            {color: '#d900ff', ionicon: 'd'},
            {color: '#d900ff', ionicon: 'e'},
            {color: '#d900ff', ionicon: 'c'},
            {color: '#d900ff', ionicon: 'c'},
            {color: '#d900ff', ionicon: 'd'},
            {color: '#d900ff', ionicon: 'e'},
            {color: '#d900ff', ionicon: 'c'},
            {color: '#d900ff', ionicon: 'e'},
            {color: '#d900ff', ionicon: 'f'},
            {color: '#d900ff', ionicon: 'g'},
            {color: '#d900ff', ionicon: 'e'},
            {color: '#d900ff', ionicon: 'f'},
            {color: '#d900ff', ionicon: 'g'},
            {color: '#d900ff', ionicon: 'g'},
            {color: '#d900ff', ionicon: 'a'},
            {color: '#d900ff', ionicon: 'g'},
            {color: '#d900ff', ionicon: 'f'},
            {color: '#d900ff', ionicon: 'e'},
            {color: '#d900ff', ionicon: 'c'},
            {color: '#d900ff', ionicon: 'g'},
            {color: '#d900ff', ionicon: 'a'},
            {color: '#d900ff', ionicon: 'g'},
            {color: '#d900ff', ionicon: 'f'},
            {color: '#d900ff', ionicon: 'e'},
            {color: '#d900ff', ionicon: 'c'},
            {color: '#d900ff', ionicon: 'c'},
            {color: '#ffb700', ionicon: 'g'},
            {color: '#d900ff', ionicon: 'c'},
            {color: '#d900ff', ionicon: 'c'},
            {color: '#ffb700', ionicon: 'g'},
            {color: '#d900ff', ionicon: 'c'}
        ]}
};