export default {
    name: 'Rock-a-bye Baby', gimmick: 'T', params: {
        id: 'id-rock-a-bye-baby', partiture: [
            {ionicon: 'b', color: '#ffb700'},
            {ionicon: 'd', color: '#d900ff'},
            {ionicon: 'b', color: '#d900ff'},
            {ionicon: 'a', color: '#d900ff'},
            {ionicon: 'g', color: '#d900ff'},
            {ionicon: 'b', color: '#ffb700'},
            {ionicon: 'd', color: '#d900ff'},
            {ionicon: 'g', color: '#d900ff'},
            {ionicon: 'f#', color: '#d900ff'},
            {ionicon: 'c', color: '#d900ff'},
            {ionicon: 'd', color: '#d900ff'},
            {ionicon: 'c', color: '#00c4ff'},
            {ionicon: 'b', color: '#d900ff'},
            {ionicon: 'a', color: '#d900ff'},
            {ionicon: 'a', color: '#d900ff'},
            {ionicon: 'g', color: '#d900ff'},
            {ionicon: 'e', color: '#d900ff'},
            {ionicon: 'd', color: '#d900ff'},
            {ionicon: 'b', color: '#ffb700'},
            {ionicon: 'd', color: '#d900ff'},
            {ionicon: 'b', color: '#d900ff'},
            {ionicon: 'a', color: '#d900ff'},
            {ionicon: 'g', color: '#d900ff'},
            {ionicon: 'b', color: '#ffb700'},
            {ionicon: 'd', color: '#d900ff'},
            {ionicon: 'g', color: '#d900ff'},
            {ionicon: 'f#', color: '#d900ff'},
            {ionicon: 'd', color: '#d900ff'},
            {ionicon: 'f#', color: '#d900ff'},
            {ionicon: 'c', color: '#00c4ff'},
            {ionicon: 'b', color: '#d900ff'},
            {ionicon: 'g', color: '#d900ff'},
            {ionicon: 'a', color: '#d900ff'},
            {ionicon: 'e', color: '#d900ff'},
            {ionicon: 'f#', color: '#d900ff'},
            {ionicon: 'g', color: '#d900ff'}
        ]}
};