export default {
    name: 'Twinkle twinkle little star', gimmick: 'T', params: {
        id: 'id04', partiture: [
            {color: '#d900ff', ionicon: 'c'},
            {color: '#d900ff', ionicon: 'c'},
            {color: '#d900ff', ionicon: 'g'},
            {color: '#d900ff', ionicon: 'g'},
            {color: '#d900ff', ionicon: 'a'},
            {color: '#d900ff', ionicon: 'a'},
            {color: '#d900ff', ionicon: 'g'},
            {color: '#d900ff', ionicon: 'f'},
            {color: '#d900ff', ionicon: 'f'},
            {color: '#d900ff', ionicon: 'e'},
            {color: '#d900ff', ionicon: 'e'},
            {color: '#d900ff', ionicon: 'd'},
            {color: '#d900ff', ionicon: 'd'},
            {color: '#d900ff', ionicon: 'c'},
            {color: '#d900ff', ionicon: 'g'},
            {color: '#d900ff', ionicon: 'g'},
            {color: '#d900ff', ionicon: 'f'},
            {color: '#d900ff', ionicon: 'f'},
            {color: '#d900ff', ionicon: 'e'},
            {color: '#d900ff', ionicon: 'e'},
            {color: '#d900ff', ionicon: 'd'},
            {color: '#d900ff', ionicon: 'g'},
            {color: '#d900ff', ionicon: 'g'},
            {color: '#d900ff', ionicon: 'f'},
            {color: '#d900ff', ionicon: 'f'},
            {color: '#d900ff', ionicon: 'e'},
            {color: '#d900ff', ionicon: 'e'},
            {color: '#d900ff', ionicon: 'd'},
            {color: '#d900ff', ionicon: 'c'},
            {color: '#d900ff', ionicon: 'c'},
            {color: '#d900ff', ionicon: 'g'},
            {color: '#d900ff', ionicon: 'g'},
            {color: '#d900ff', ionicon: 'a'},
            {color: '#d900ff', ionicon: 'a'},
            {color: '#d900ff', ionicon: 'g'},
            {color: '#d900ff', ionicon: 'f'},
            {color: '#d900ff', ionicon: 'f'},
            {color: '#d900ff', ionicon: 'e'},
            {color: '#d900ff', ionicon: 'e'},
            {color: '#d900ff', ionicon: 'd'},
            {color: '#d900ff', ionicon: 'd'},
            {color: '#d900ff', ionicon: 'c'}
        ]
    }
};